version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: app_backend
    restart: unless-stopped
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./backend:/app:delegated
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=app_password
    entrypoint: ["/app/docker/entrypoint.sh"]
    networks:
      - app_network

  frontend:
    image: node:18-alpine
    container_name: app_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NUXT_API_BASE=http://backend:80
      - NUXT_PUBLIC_API_BASE=http://localhost:8000
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8084:80"
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:
  frontend_node_modules:

networks:
  app_network:
    driver: bridge
